### ISSUE TITLE
Why use this code in setup_object.sh

### ISSUE THREAD

**Issue by BWbwchen** [jmodares/UB-ANC-Emulator#1]
Hello , I am trying to use this emulator, and when I try to setup object with the setup_object.sh
I found the process stuck at this line.
https://github.com/jmodares/UB-ANC-Emulator/blob/0f709e22358fdd56b66bc5979a87b7022a106b20/script/setup_objects.sh#L27
So I want to know why need this code?
Thanks you :)

**Comment by nmastron** [comment]
Thank you for opening this issue. We have encountered this locally as well. We are looking for a solution.

This line is needed because agent i communicates with its SITL (the software-in-the-loop flight control firmware) over port 10 * i + STL_PORT + 3 (where STL_PORT is 5760), so these ports need to be available. Even if you comment this out in setup_objects.sh, you'll run into the problem again in start_emulator.sh.

**Comment by hariprasath95** [comment]
Can you run  "nc -z localhost 5773" before running the application and check if something else is running, This might be because port 5773 might be blocked by some other application.

**Comment by nmastron** [comment]
The communication between agents and emulator are based on TCP ports and network connection, so, it is very important to check if all ports are open and free to use, like:
nc -z localhost 5773 

The Emulator needs TCP port to be open and free to use, if for any reason (firewall, proxy security, ...) the ports are closed, we will encounter the problem (in any stage, setup up objects, running emulator, ...).
The best way to run the emulator is to use VM with Ubuntu 16.04, and make sure all ports are open. (it is dangerous to disable firewall on real Linux servers).

If ports are not free, we have to disable firewall, proxy, or, kill all firmware, agents, which remain from previous run.
killall arducopter
killall agent
killall emulator

There are also some good network utilities on linux that can help, for instance:
lsof -n -i4TCP:5773

It will show information about who is using the port.

lsof -n -i4TCP will show all used ports

I hope this helps.

**Comment by BWbwchen** [comment]
@nmastron thanks you !!
@hariprasath95 after i restart my computer and it can work ! thx !
