### ISSUE TITLE
Cannot create platform OpenGL context, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by BWbwchen** [jmodares/UB-ANC-Emulator#2]
When I try to start the emulator with start_emulator.sh , I get this
```
Request for unknown firmware plugin factory 12
qml: 0.049479166666666664
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qml: 34.5 38
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayViewVideo.qml:32: TypeError: Cannot read property 'videoRunning' of null
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayViewVideo.qml:44: TypeError: Cannot read property 'videoRunning' of null
qrc:///qml/QGroundControl/FlightMap/QGCVideoBackground.qml:25:14: Unable to assign [undefined] to VideoSurface*
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayViewVideo.qml:52: TypeError: Cannot read property 'videoRunning' of null
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayViewVideo.qml:51: TypeError: Cannot read property 'videoSurface' of null
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayView.qml:374: TypeError: Cannot read property 'videoRunning' of null
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
./start_emulator.sh: line 127: 12822 Aborted                 (core dumped) ./emulator --clear-settings --ChecksumEnabled=false --ns3::YansWifiChannel::PropagationDelayModel=ns3::ConstantSpeedPropagationDelayModel --ns3::YansWifiChannel::PropagationLossModel=ns3::FriisPropagationLossModel --ns3::WifiPhy::RxGain=-10 --ns3::WifiRemoteStationManager::NonUnicastMode=DsssRate1Mbps --ns3::ConstantRateWifiManager::DataMode=DsssRate1Mbps --ns3::ConstantRateWifiManager::ControlMode=DsssRate1Mbps
```
Can anyone help me ?
Thanks you :)

**Comment by nmastron** [comment]
This is most likely related to your system. I did a quick search on Google for "Qgroundcontrol QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled" and found a number of entries about this. I recommend checking the suggested solutions.

**Comment by jmodares** [comment]
Could you please confirm if you were using VM with a fresh 64-bit Ubuntu
16.04 and required modules:

sudo apt-get install build-essential \
    libgl1-mesa-dev libsdl2-dev python-future \
    libfontconfig1 dbus-x11 geoclue curl git netcat xvfb

**Comment by BWbwchen** [comment]
I use server for this project , so maybe there are something about permission that I don't have (?
@jmodares  yes, i had already install all the necessary package and compile the emulator and follower well done. So I have no idea what's wrong...
Thanks you:)

**Comment by BWbwchen** [comment]
@nmastron  thanks for your help, and I googled a solution [here](https://github.com/qutebrowser/qutebrowser/issues/3276#issuecomment-347689668), but it didn't work for me ...

**Comment by jmodares** [comment]
By 'I use server' I assume you are using actual Linux server (not virtual machine) with no desktop environment (X server).

If that's true, please try it on Ubuntu 16.04 64-Bit Desktop version on virtual machine for security purpose.

I hope that helps.

**Comment by BWbwchen** [comment]
I solve it !
I change to use pc and it work !
It seems that it is server's graphic card driver problem...
